name: RezxisMCHosting
main: net.rezxis.mchosting.lobby.Lobby
version: 0.2
softdepend: [Votifier]
depend: [RezxisSQLPlugin]
commands:
  menu:
    description: Show RezxisRealms menu
  menu2:
    description: Show RezxisRealms menu
  manage:
    description: Show RezxisRealms menu
  servers:
    description: Show RezxisRealms menu
  connect:
    description: Connect to my server
  stopall:
    description: A command for staffs
  crate:
    description: Show RezxisRealms menu
  manager:
    description: Manage all servers
  prefix:
    description: A command to change prefix
  fly:
    description: A command to allow fly
  thirdparty:
    description: A command to manage thirdparty
  rankinfo:
    description: A command to check your rank
  voteinfo:
    description: A commant to check you vote status
  makevote:
    description: debug