name: RezxisMCHosting
main: net.rezxis.mchosting.lobby.Lobby
version: 0.2
commands:
  menu:
    description: Show RezxisRealms menu
  menu2:
    description: Show RezxisRealms menu
  manage:
    description: Show RezxisRealms menu
  servers:
    description: Show RezxisRealms menu
  connect:
    description: Connect to my server
  stopall:
    description: A command for staffs
  crate:
    description: Show RezxisRealms menu
  manager:
    description: Manage all servers
  vote:
    description: Vote to child server.